services:
  web:
    build:
      context: .
    command: uvicorn ifcb_annotate.asgi:application --host 0.0.0.0 --port 8000 --limit-concurrency 2000 --workers 16 --backlog 5000
    network_mode: "host"
    environment:
      POSTGRES_HOST: "localhost"
    env_file:
      - .env
    volumes:
      - .:/app
      - annotate_static:/static
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d:ro
      - annotate_static:/static:ro
      - ${NGINX_LOG_DIR:-./logs/nginx}:/var/log/nginx
      - type: bind
        source: ${SSL_CERT_PATH:-./ssl/server.crt}
        target: /etc/ssl/server.crt
        read_only: true
      - type: bind
        source: ${SSL_KEY_PATH:-./ssl/server.key}
        target: /etc/ssl/server.key
        read_only: true
    ports:
      - 8080:80
      - 8443:443
    networks:
      - ifcb_annotate
    depends_on:
      - web
    restart: unless-stopped

  db:
    image: postgres:17.2-alpine
    command: postgres -c max_connections=300
    environment:
      POSTGRES_HOST: "${POSTGRES_HOST:-db}"
    env_file:
      - .env
    volumes:
      # To use a folder location on the host
      - ${POSTGRES_DATA:-/srv/ifcb-annotate}:/var/lib/postgresql/data
      # To use a docker-managed volume. You must also uncomment the volumes section further down
      #- ifcb_annotate_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ifcb_annotate
    restart: unless-stopped
    healthcheck:
      test: "pg_isready -h db"
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 3s

networks:
  ifcb_annotate:
    name: ifcb_annotate
    driver: bridge

volumes:
  annotate_static:
  