# Generated by Django 5.1.6 on 2025-02-12 04:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('international_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'classify_classlabel',
            },
        ),
        migrations.CreateModel(
            name='TagLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'classify_taglabel',
            },
        ),
        migrations.CreateModel(
            name='Timeseries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Timeseries',
                'db_table': 'classify_timeseries',
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin', models.CharField(max_length=100)),
                ('roi', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('classification_id', models.IntegerField()),
                ('level', models.IntegerField(default=1)),
                ('verifications', models.IntegerField(default=0)),
                ('verification_time', models.DateTimeField(blank=True, null=True)),
                ('timeseries_id', models.CharField(max_length=36)),
            ],
            options={
                'db_table': 'classify_classification',
                'indexes': [models.Index(fields=['bin'], name='classify_cl_bin_60d347_idx')],
                'unique_together': {('bin', 'roi', 'user_id', 'classification_id')},
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin', models.CharField(max_length=100)),
                ('roi', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('tag_id', models.IntegerField()),
                ('level', models.IntegerField(default=1)),
                ('verifications', models.IntegerField(default=0)),
                ('verification_time', models.DateTimeField(blank=True, null=True)),
                ('timeseries_id', models.CharField(max_length=36)),
                ('negation', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'classify_tag',
                'indexes': [models.Index(fields=['tag_id'], name='classify_ta_tag_id_8c2a64_idx')],
                'unique_together': {('bin', 'roi', 'user_id', 'tag_id', 'negation')},
            },
        ),
    ]
